minikube: 1.2.0 (new formula)
Linuxbrew/homebrew-extra pull request #54
Opened 2019-06-26 22:44 UTC by issyl0

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Linuxbrew/homebrew-extra/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Linuxbrew/homebrew-xorg/pulls) for the same update/change?
- [x] ~Have you included a log of the failed build without your patch using `brew gist-logs <formula>`?~
- [x] Does your submission pass
`brew audit --strict <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

---

- Minikube, like aws-vault, was only available in Homebrew Cask for MacOS.
- This adds a formula that builds on Linux (tested on Ubuntu 18.04).

2019-06-27 00:10 UTC, sjackman requested changes

2019-06-27 00:10 UTC, sjackman commented on Formula/minikube.rb
> +    end
```ruby
bin.install "out/minikube"
```

2019-06-30 14:45 UTC, issyl0 commented on Formula/minikube.rb
> +    end
Thanks - done!

2019-06-30 17:10 UTC, sjackman approved these changes

2019-06-30 21:22 UTC, closed without merging